export const UUID_KEY = '__BR_UUID__'
export const REPORT_REQUEST = '__BR_REPORT__'
export const COLLECT_INFO = '__BR_COLLECT_INFO__'
export const PERF_INFO = '__BR_PERF_INFO__'
export const COLLECT_ERROR = '__BR_COLLECT_ERROR__'
export const REPORT_QUEUE = '$$__BR_REPORT_QUEUE__'
export const COLLECT_API = '__BR_API__'
