[package]
name = "sign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
js-sys = "0.3.66"
md5 = "0.7.0"
serde_json = "1.0.108"
wasm-bindgen = "0.2.89"

[lib]
crate-type = ["cdylib", "rlib"]

